#!/bin/bash

if ! { ruby --version | grep -q '^ruby 1.9.3'; }
then
  echo "Zone verification tests fail without Ruby 1.9.3." >&2
fi

if [ "$TRAVIS" = "true" ]; then
  # Install a Ruby 1.9.3 for to get a `strftime` that understands `%::z`.
  ruby -v
  which ruby
  echo ""
  (cd src && ../util/sizes timezone.js rfc822.js)
  echo ""
fi

ls -la build/timezone/index.js

echo ""

(proof run t/*/*.t.* t/*/*/*.t.* | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ] || [ "$MINIFY" = "true" ]; then
  default=$(cat src/timezone.js | uglifyjs | gzip -c | wc -c)
  lift=$(cat src/timezone.js | uglifyjs --lift-vars | gzip -c | wc -c)

  if [ $default -lt $lift ]; then
    cat src/timezone.js | uglifyjs > build/timezone/index.js
  else
    cat src/timezone.js | uglifyjs --lift-vars > build/timezone/index.js
  fi 
 
  ls -la build/timezone/index.js

  echo ""

  (proof run t/*/*.t.* t/locale/*/*.t.* t/zones/timezone/*.t.* | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1
fi
